### ISSUE TITLE
>tfw Jack doesn't know how to license properly

### ISSUE THREAD

**Issue by trevor229** [Dizeeee/FIGbot#1]
`(As a small footnote, please don't remove my name and the donation address from the help command. I know that you are totally allowed to change anything you want under this licensing, but I would like to keep my username attached to the bot. IDC if you change or add anything else though.)`

ni🅱️🅱️a

You're describing a [Creative Commons Attribution 4.0 International (CC BY 4.0) License](https://creativecommons.org/licenses/by/4.0/legalcode)
[(Here's a Human-Readable copy)](https://creativecommons.org/licenses/by/4.0/)

The CC BY 4.0 License allows an individual to:

- Share, copy, and redistribute the material in any medium or format
- Adapt, remix, transform, and build upon the material
for any purpose, even commercially.

While still explicitly requiring credit to the original creator as you described by saying:
`...I would like to keep my username attached to the bot. IDC if you change or add anything else though.`

To change to the CC BY 4.0 License, just edit the LICENSE.md file and copy the [legal text of the license](https://creativecommons.org/licenses/by/4.0/legalcode) and saving it while notifying individuals by posting "This work is licensed under a Creative Commons Attribution 4.0 International License." in the README.md file.

Keep in mind, Alongside the fact that you are NOT limited to the license templates that GitHub provides you, you cannot just say "Lol sorry now it's under a CC BY 4.0 License, not BSD-3-Clause" The current source code is licensed and will always be licensed under the BSD-3-Clause License because it has been grandfathered in by U.S. copyright law. To change the license, you simply have to release the next version of the source code as CC BY 4.0 to operate under that license.

And as another note, you will be credited according to the terms of the license, although the users do not have to include your donation address in the source. A better and more effective way of getting possible donations would be to post it in the README file saying something along the lines of "If you like this software, please consider sending a small tip my way".

**Comment by 16ajans** [comment]
gg

**Comment by jackmalcom** [comment]
Actually, I believe I'm still forced to distribute it under under BSD-3 Clause because it's what FIGlet uses. I just added that string in as a way for end users to see that I wrote the bot without needing to read my copyright in the license. Feel free to correct me if I am wrong but that about footer could be removed.

**Comment by trevor229** [comment]
I understand your reasoning. Although according to the BSD-3-Clause license:

- Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

- Redistributions of **source code** must retain the above copyright notice, this list of conditions and the following disclaimer.

You are not redistributing source code materials, only code that YOU have written and used to INTERFACE with the application.

- Redistributions in **binary form must reproduce the above copyright notice**, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

Your script obviously isn't a binary so this does not apply here.

- Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

I highly doubt you'd do this, so we're good here too.

So, according to the license, since you are not redistributing in whole or part any of FIGlet's source code or modifying it in any way, only interfacing with it through a Python script, you should be able to re-license your new version of software under CC-BY-4.0 since you are not breaking any of the three clauses  stated in the license.
